FROM registry.opensuse.org/opensuse/leap:16.0

RUN zypper in --no-recommends -y binutils cmake findutils gawk git lldb ninja &&\
    zypper clean --all &&\
    useradd code

USER code

# Update path for zig from extension
ENV PATH=${PATH}:/home/code/.local/bin:/home/code/.cursor-server/data/User/globalStorage/ziglang.vscode-zig/zig/x86_64-linux-0.16.0