# ApplyRedef.cmake — script-mode helper invoked at build time.
#
# Reads a fuzzmate redefinition file and applies objcopy --redefine-sym /
# --globalize-symbol to each listed object file so that file-local (static)
# symbols become globally visible under their mangled names.
#
# Expected -D variables:
#   REDEF_FILE    — path to the fuzzmate-generated .redef file
#   OBJ_LIST_FILE — path to a text file listing one object-file path per line
#                   (generated by file(GENERATE) from $<TARGET_OBJECTS:...>)
#   OBJCOPY       — path to the objcopy (or llvm-objcopy) executable

if(NOT EXISTS "${REDEF_FILE}")
    # Empty or missing redef file means no static symbols — nothing to do.
    return()
endif()

# ── Load object file list ────────────────────────────────────────────────
if(NOT EXISTS "${OBJ_LIST_FILE}")
    message(FATAL_ERROR "ApplyRedef: object list file not found: ${OBJ_LIST_FILE}")
endif()

file(STRINGS "${OBJ_LIST_FILE}" _obj_paths)

# ── Process redefinitions ────────────────────────────────────────────────
file(STRINGS "${REDEF_FILE}" _lines)
foreach(_line ${_lines})
    # Each line: "<source_path> <old_symbol> <new_symbol>"
    string(REPLACE " " ";" _parts "${_line}")
    list(LENGTH _parts _len)
    if(NOT _len EQUAL 3)
        continue()
    endif()
    list(GET _parts 0 _src_file)
    list(GET _parts 1 _old_sym)
    list(GET _parts 2 _new_sym)

    # Find the object file whose path ends with <source_path>.o.
    # CMake Ninja generator replaces "../" with "__/" in object paths,
    # so we try both the literal source path and the Ninja-normalized form.
    string(REPLACE "../" "__/" _src_ninja "${_src_file}")

    set(_obj "")
    foreach(_candidate ${_obj_paths})
        # Match suffix: /src/decoder.c.o or __/src/decoder.c.o
        if(_candidate MATCHES "/${_src_file}\\.o$"
           OR _candidate MATCHES "/${_src_ninja}\\.o$")
            set(_obj "${_candidate}")
            break()
        endif()
    endforeach()

    if(NOT _obj)
        message(FATAL_ERROR
            "ApplyRedef: no object file found for source '${_src_file}'.\n"
            "  Looked for suffix '${_src_file}.o' (and '${_src_ninja}.o') in:\n"
            "  ${OBJ_LIST_FILE}")
    endif()

    execute_process(
        COMMAND "${OBJCOPY}" "--redefine-sym" "${_old_sym}=${_new_sym}" "${_obj}"
        RESULT_VARIABLE _rc)
    if(NOT _rc EQUAL 0)
        message(FATAL_ERROR "objcopy --redefine-sym failed for ${_obj}")
    endif()

    execute_process(
        COMMAND "${OBJCOPY}" "--globalize-symbol" "${_new_sym}" "${_obj}"
        RESULT_VARIABLE _rc)
    if(NOT _rc EQUAL 0)
        message(FATAL_ERROR "objcopy --globalize-symbol failed for ${_obj}")
    endif()
endforeach()
